import type { Metadata } from "next";
import { Nunito, PT_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { cookies } from "next/headers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const nunito = Nunito({
	variable: "--font-nunito",
	subsets: ["latin"],
});

const ptSans = PT_Sans({
	variable: "--font-pt-sans",
	subsets: ["latin"],
	weight: ["400", "700"],
});

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const theme = cookieStore.get("theme")?.value ?? "light";

	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${nunito.variable} ${
						ptSans.variable
					} antialiased relative ${
						theme !== "dark" ? "light" : "dark"
					}`}
				>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
